/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated.upload'
import { Route as AuthenticatedAnalysesIndexRouteImport } from './routes/_authenticated.analyses.index'
import { Route as AuthenticatedAnalysesAnalysisIDRouteImport } from './routes/_authenticated.analyses.$analysisID'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysesIndexRoute =
  AuthenticatedAnalysesIndexRouteImport.update({
    id: '/analyses/',
    path: '/analyses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalysesAnalysisIDRoute =
  AuthenticatedAnalysesAnalysisIDRouteImport.update({
    id: '/analyses/$analysisID',
    path: '/analyses/$analysisID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/analyses/$analysisID': typeof AuthenticatedAnalysesAnalysisIDRoute
  '/analyses/': typeof AuthenticatedAnalysesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/analyses/$analysisID': typeof AuthenticatedAnalysesAnalysisIDRoute
  '/analyses': typeof AuthenticatedAnalysesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/analyses/$analysisID': typeof AuthenticatedAnalysesAnalysisIDRoute
  '/_authenticated/analyses/': typeof AuthenticatedAnalysesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/upload'
    | '/analyses/$analysisID'
    | '/analyses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/upload'
    | '/analyses/$analysisID'
    | '/analyses'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/upload'
    | '/_authenticated/analyses/$analysisID'
    | '/_authenticated/analyses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses/': {
      id: '/_authenticated/analyses/'
      path: '/analyses'
      fullPath: '/analyses/'
      preLoaderRoute: typeof AuthenticatedAnalysesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses/$analysisID': {
      id: '/_authenticated/analyses/$analysisID'
      path: '/analyses/$analysisID'
      fullPath: '/analyses/$analysisID'
      preLoaderRoute: typeof AuthenticatedAnalysesAnalysisIDRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedAnalysesAnalysisIDRoute: typeof AuthenticatedAnalysesAnalysisIDRoute
  AuthenticatedAnalysesIndexRoute: typeof AuthenticatedAnalysesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedAnalysesAnalysisIDRoute: AuthenticatedAnalysesAnalysisIDRoute,
  AuthenticatedAnalysesIndexRoute: AuthenticatedAnalysesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
